theme: just-the-docs
color_scheme: dark
url: https://destinyweaves.github.io/
plugins:
  - jekyll-default-layout
  - jekyll-remote-theme
remote_theme: just-the-docs/just-the-docs

logo: "/assets/images/logo.png"
favicon_ico: "/assets/images/favicon.png"

title: Destiny Weaves Guidebook
description: Guidebook for the Destiny Weaves Pern Roleplay Game on JcInk
aux_links:
  Forum: https://destinyweaves.jcink.net/
  Discord: https://discord.gg/4SgEpuzqYR
  Github: https://github.com/DestinyWeaves/Guidebook/
