title: Destiny Weaves Guidebook
description: Guidebook for the Destiny Weaves Pern Roleplay Game on JcInk
theme: just-the-docs

url: https://destinyweaves.github.io

aux_links:
  Forum: https://destinyweaves.jcink.net/
  Discord: https://discord.gg/4SgEpuzqYR
  Github: https://github.com/DestinyWeaves/Guidebook/